#!/bin/bash
#Factor5 Package Build / Verification System for TCLinux
echo "Not Ready For Production Yet"
echo "verify that you have read the shell script and know what you want to do"
echo "type n to exit"
read $in

if [[ $in = 'n' ]]
then
	exit
fi


#TCE="/mnt/sda1/tce"
#TCE=$(tce-setdrive | cut -d "," -f 2)
TCE=/mnt/mmcblk0p2/

if [[ $1 = "build" ]]
then
	if [ -d ./BuildRoot ]; then
	echo "directory exists do you want to clean it"
    fi
	read $in
		if [[ $in = "yes" || $in = "y" ]]
		then
			rm ./BuildRoot -R
			mkdir BuildRoot
		else
			mkdir BuildRoot
			echo "place files into BuildRoot"
			read
			mksquashfs ./BuildRoot $2.tcz
			md5sum $2.tcz > $2.tcz.md5.txt
		fi
fi

if [[ $1 = "extract" ]]
then
    unsquish $2
fi

#installs itself
if [[ $1 = "install" ]]
then
	cp $2.tcz $TCE/optional
	echo "$2.tcz" >> $TCE/onboot.lst
	#if $2=all
	#cp ./Packages/ $home/tce/optional
fi

if [[ $1 = "clean" ]]
then
	rm ./BuildRoot -R
fi

if [[ $1 = "server" ]]
then
	#python -m SimpleHTTPServer 8080
	python3 -m http.server 8080
fi

if [[ $1 = "sshkeys" ]]
then
    ssh-keygen
fi

if [[ $1 = "compile" ]]
then
    ./Build
    ./autogen.sh
    ./bootstrap.sh
    aclocal
    libtoolize -i
    autoreconf -i
    automake --add-missing
    ./configure
    make && make install DESTDIR=../BuildRoot
  
fi




